---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  labels:
    project: whoami
    environment: sandbox
    team: losdevops
    product-owner: jorge-medina
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/whoami
    repoURL: https://github.com/jorgearma1982/infra-configs.git
    targetRevision: HEAD
